In [125]:
import numpy as np
import pandas as pd
from scipy.sparse.linalg import eigs 
import scipy.linalg as lin

from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
import plotly.graph_objs as go

init_notebook_mode(connected=True)

In [126]:
# Generate clustering data
from sklearn.datasets.samples_generator import make_blobs
from scipy.stats import multivariate_normal

k = 2

centers = np.zeros((k,2))

XX, y_true = make_blobs(n_samples=400, centers=k,
                       cluster_std=1, random_state=2)

rng = np.random.RandomState(13)

A = np.where(y_true==0)
B = np.where(y_true==1)

XA = np.dot(XX[A,:], rng.randn(2, 2))
rng = np.random.RandomState(13)
XB = np.dot(XX[B,:], rng.randn(2, 2))


X = np.zeros((400,2))

X[0:200,:] = XA[:,:]
X[200:400,:] = XB[:,:]



In [127]:

centers[0,:] = [-2,2.5]
centers[1,:] = [-1,3]

pi = [0.5,0.5]

Sigma1 = np.identity(2)
Sigma2 = np.identity(2)


print(centers)

[[-2.   2.5]
 [-1.   3. ]]


In [128]:
n_iter = 50
n = 400
c = np.zeros((n,1))
d = np.zeros((k,1))
Q = np.zeros((n,2))

for m in range(n_iter):
    c = np.argmax(Q,1)
    A = np.where(c==0)
    B = np.where(c==1)
    scatter = go.Scatter(
    x = X[A[0],0],
    y = X[A[0],1],
    mode='markers',
    marker=dict(
            size=5,
            symbol='circle',
            color='blue',
            opacity=1
        )
    )
    scatter1 = go.Scatter(
        x = X[B[0],0],
        y = X[B[0],1],
        mode='markers',
        marker=dict(
            size=5,
            symbol='circle',
            color='red',
            opacity=1
        )
    )

    
    scatter4 = go.Scatter(
        x = centers[:,0],
        y = centers[:,1],
        mode='markers',
        marker=dict(
            size=8,
            symbol='star',
            color='black',
            opacity=1
        )
    )
    # Above code is for scatter plot of every iteration.

    data = [scatter,scatter1,scatter4]
    iplot(data, filename='fig0')
    # Assign clusters
    print(Sigma1)
    print(Sigma2)
    for i in range(n):
        #d[0] = (X[i,:] - centers[0,:])@Sigma1@(X[i,:] - centers[0,:]).T/2 - np.log(pi[0])
        #d[1] = (X[i,:] - centers[1,:])@Sigma2@(X[i,:] - centers[1,:]).T/2 - np.log(pi[1])
        #c[i] = np.argmin(d)

        var1 = multivariate_normal(mean=centers[0,:], cov=Sigma1)
        var2 = multivariate_normal(mean=centers[1,:], cov=Sigma2)
        Q[i,0] = var1.pdf(X[i,:])*pi[0]
        Q[i,1] = var2.pdf(X[i,:])*pi[1]
        sm =  Q[i,1] + Q[i,0]
        Q[i,0] = Q[i,0]/sm
        Q[i,1] = Q[i,1]/sm
    data = []
    
    # Compute Means and ellipsoids
    centers[0,:] = X.T@Q[:,0]/sum(Q[:,0])
    centers[1,:] = X.T@Q[:,1]/sum(Q[:,1])
    Sigma1 = np.zeros((2,2))
    Sigma2 = np.zeros((2,2))
    for t in range(n):
        Sigma1 = Sigma1 + Q[t,0]*np.asmatrix(X[t,:] - centers[0,:]).T@np.asmatrix(X[t,:] - centers[0,:])/sum(Q[:,0])
        Sigma2 = Sigma2 + Q[t,1]*np.asmatrix(X[t,:] - centers[1,:]).T@np.asmatrix(X[t,:] - centers[1,:])/sum(Q[:,1])
    pi[1] =  sum(Q[:,1])/n
    pi[0] = sum(Q[:,0])/n
        
        
    

        
    


[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


[[ 1.46872111 -3.11195368]
 [-3.11195368  7.63860485]]
[[ 1.42563726 -3.01963878]
 [-3.01963878  7.37793502]]


[[ 1.47222454 -3.11263371]
 [-3.11263371  7.6398494 ]]
[[ 1.41685209 -3.01189699]
 [-3.01189699  7.35293886]]


[[ 1.47557176 -3.1124825 ]
 [-3.1124825   7.6356415 ]]
[[ 1.40814374 -3.00482241]
 [-3.00482241  7.33470908]]


[[ 1.47961349 -3.11384793]
 [-3.11384793  7.63276849]]
[[ 1.39765573 -2.99331471]
 [-2.99331471  7.30911101]]


[[ 1.48433228 -3.11669768]
 [-3.11669768  7.63147451]]
[[ 1.38533424 -2.97714172]
 [-2.97714172  7.27502407]]


[[ 1.48963892 -3.12079454]
 [-3.12079454  7.63138633]]
[[ 1.37125242 -2.95644967]
 [-2.95644967  7.23238543]]


[[ 1.49544636 -3.12590414]
 [-3.12590414  7.63209093]]
[[ 1.35544945 -2.93131421]
 [-2.93131421  7.18098784]]


[[ 1.50167134 -3.13180489]
 [-3.13180489  7.63317335]]
[[ 1.33791839 -2.90169219]
 [-2.90169219  7.12034092]]


[[ 1.50822947 -3.13827823]
 [-3.13827823  7.63419783]]
[[ 1.31860499 -2.86740596]
 [-2.86740596  7.04961603]]


[[ 1.51502943 -3.14509576]
 [-3.14509576  7.63467867]]
[[ 1.29740281 -2.82811911]
 [-2.82811911  6.96756473]]


[[ 1.52196656 -3.15200382]
 [-3.15200382  7.63404139]]
[[ 1.27414085 -2.78329226]
 [-2.78329226  6.8723798 ]]


[[ 1.52891486 -3.15870308]
 [-3.15870308  7.63156715]]
[[ 1.24855905 -2.7321048 ]
 [-2.7321048   6.76146047]]


[[ 1.535716   -3.16481874]
 [-3.16481874  7.62630707]]
[[ 1.22026286 -2.67331781]
 [-2.67331781  6.6310138 ]]


[[ 1.54216217 -3.16985271]
 [-3.16985271  7.61694042]]
[[ 1.18864102 -2.60503247]
 [-2.60503247  6.47536472]]


[[ 1.54796632 -3.17309967]
 [-3.17309967  7.60152434]]
[[ 1.15271547 -2.52425435]
 [-2.52425435  6.28572376]]


[[ 1.55270525 -3.17348747]
 [-3.17348747  7.57702166]]
[[ 1.11085998 -2.42607976]
 [-2.42607976  6.04789407]]


[[ 1.55570146 -3.16924912]
 [-3.16924912  7.53834529]]
[[ 1.06024999 -2.30210394]
 [-2.30210394  5.73778795]]


[[ 1.55575723 -3.15719133]
 [-3.15719133  7.47626354]]
[[ 0.9957357  -2.13715174]
 [-2.13715174  5.31221067]]


[[ 1.55050183 -3.13090639]
 [-3.13090639  7.37236807]]
[[ 0.90749279 -1.90242491]
 [-1.90242491  4.68950806]]


[[ 1.53463974 -3.07595995]
 [-3.07595995  7.18577187]]
[[ 0.77695326 -1.54337499]
 [-1.54337499  3.71509774]]


[[ 1.4950413  -2.95617464]
 [-2.95617464  6.81596487]]
[[ 0.58222431 -0.99263114]
 [-0.99263114  2.19536554]]


[[ 1.3968495  -2.6751842 ]
 [-2.6751842   6.00484641]]
[[ 0.41299667 -0.48491504]
 [-0.48491504  0.7668535 ]]


[[ 1.13648794 -2.00582004]
 [-2.00582004  4.26673476]]
[[ 0.43448892 -0.45932546]
 [-0.45932546  0.62404367]]


[[ 0.77033059 -1.13746405]
 [-1.13746405  2.18822141]]
[[ 0.47601457 -0.49708463]
 [-0.49708463  0.65769494]]


[[ 0.57035953 -0.63780244]
 [-0.63780244  0.94768013]]
[[ 0.48457159 -0.51206429]
 [-0.51206429  0.69217041]]


[[ 0.55756221 -0.59238641]
 [-0.59238641  0.80229806]]
[[ 0.48967393 -0.52484956]
 [-0.52484956  0.71938301]]


[[ 0.5575613  -0.59237156]
 [-0.59237156  0.80222772]]
[[ 0.48968101 -0.52486509]
 [-0.52486509  0.71941311]]


[[ 0.5575613  -0.59237156]
 [-0.59237156  0.80222771]]
[[ 0.48968101 -0.52486509]
 [-0.52486509  0.71941311]]


[[ 0.5575613  -0.59237156]
 [-0.59237156  0.80222771]]
[[ 0.48968101 -0.52486509]
 [-0.52486509  0.71941311]]


[[ 0.5575613  -0.59237156]
 [-0.59237156  0.80222771]]
[[ 0.48968101 -0.52486509]
 [-0.52486509  0.71941311]]


[[ 0.5575613  -0.59237156]
 [-0.59237156  0.80222771]]
[[ 0.48968101 -0.52486509]
 [-0.52486509  0.71941311]]


[[ 0.5575613  -0.59237156]
 [-0.59237156  0.80222771]]
[[ 0.48968101 -0.52486509]
 [-0.52486509  0.71941311]]


[[ 0.5575613  -0.59237156]
 [-0.59237156  0.80222771]]
[[ 0.48968101 -0.52486509]
 [-0.52486509  0.71941311]]


[[ 0.5575613  -0.59237156]
 [-0.59237156  0.80222771]]
[[ 0.48968101 -0.52486509]
 [-0.52486509  0.71941311]]


[[ 0.5575613  -0.59237156]
 [-0.59237156  0.80222771]]
[[ 0.48968101 -0.52486509]
 [-0.52486509  0.71941311]]


[[ 0.5575613  -0.59237156]
 [-0.59237156  0.80222771]]
[[ 0.48968101 -0.52486509]
 [-0.52486509  0.71941311]]


[[ 0.5575613  -0.59237156]
 [-0.59237156  0.80222771]]
[[ 0.48968101 -0.52486509]
 [-0.52486509  0.71941311]]


[[ 0.5575613  -0.59237156]
 [-0.59237156  0.80222771]]
[[ 0.48968101 -0.52486509]
 [-0.52486509  0.71941311]]


[[ 0.5575613  -0.59237156]
 [-0.59237156  0.80222771]]
[[ 0.48968101 -0.52486509]
 [-0.52486509  0.71941311]]


[[ 0.5575613  -0.59237156]
 [-0.59237156  0.80222771]]
[[ 0.48968101 -0.52486509]
 [-0.52486509  0.71941311]]


[[ 0.5575613  -0.59237156]
 [-0.59237156  0.80222771]]
[[ 0.48968101 -0.52486509]
 [-0.52486509  0.71941311]]


[[ 0.5575613  -0.59237156]
 [-0.59237156  0.80222771]]
[[ 0.48968101 -0.52486509]
 [-0.52486509  0.71941311]]


[[ 0.5575613  -0.59237156]
 [-0.59237156  0.80222771]]
[[ 0.48968101 -0.52486509]
 [-0.52486509  0.71941311]]


[[ 0.5575613  -0.59237156]
 [-0.59237156  0.80222771]]
[[ 0.48968101 -0.52486509]
 [-0.52486509  0.71941311]]


[[ 0.5575613  -0.59237156]
 [-0.59237156  0.80222771]]
[[ 0.48968101 -0.52486509]
 [-0.52486509  0.71941311]]


[[ 0.5575613  -0.59237156]
 [-0.59237156  0.80222771]]
[[ 0.48968101 -0.52486509]
 [-0.52486509  0.71941311]]


[[ 0.5575613  -0.59237156]
 [-0.59237156  0.80222771]]
[[ 0.48968101 -0.52486509]
 [-0.52486509  0.71941311]]


[[ 0.5575613  -0.59237156]
 [-0.59237156  0.80222771]]
[[ 0.48968101 -0.52486509]
 [-0.52486509  0.71941311]]


[[ 0.5575613  -0.59237156]
 [-0.59237156  0.80222771]]
[[ 0.48968101 -0.52486509]
 [-0.52486509  0.71941311]]
