In [2]:
import numpy as np
import pandas as pd
from scipy.cluster.hierarchy import dendrogram, linkage
from scipy.cluster.hierarchy import fcluster

# load iris data
df_iris = pd.read_csv('./iris.csv')

In [3]:
# in Y store labels and in X just the data

n = df_iris.values.shape[0]

Y = np.zeros((n,1))
for i in range(n):
    if(df_iris.values[i,4]=='setosa'):
        Y[i,0] = 1
    else:
        if(df_iris.values[i,4]=='versicolor'):
            Y[i,0] = 2
        else:
            Y[i,0] = 3

X = df_iris.values[:,0:4];



In [4]:
# PErform single linkage clustering and find 3 clusters
Z = linkage(X, 'single')
max_d = 3
clusters = fcluster(Z, max_d,criterion='maxclust')

In [5]:
# Compare with true lables
A = np.zeros((n,2))
A[:,0] = Y[:,0]
A[:,1] = clusters
print(A)



[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]

In [6]:
# PErform average linkage clustering and find 3 clusters
Z = linkage(X, 'average')
max_d = 3
clusters = fcluster(Z, max_d,criterion='maxclust')

In [7]:
# Compare with true lables
A = np.zeros((n,2))
A[:,0] = Y[:,0]
A[:,1] = clusters
print(A)

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]

In [12]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=3, random_state=0).fit(X)
clusters = 1 + kmeans.labels_

In [13]:

A = np.zeros((n,2))
A[:,0] = Y[:,0]
A[:,1] = clusters
print(A)

[[ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  3.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  3.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]
 [ 2.  1.]